BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOG_AUDITORIA';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INSCRICOES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE USUARIOS (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PRIORIDADE NUMBER(1) CHECK (PRIORIDADE BETWEEN 1 AND 3),
    SALDO NUMBER(10,2) DEFAULT 0 NOT NULL
)
/

CREATE TABLE INSCRICOES (
    ID NUMBER PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    VALOR_PAGO NUMBER(10,2) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_INSCRICOES_USUARIOS FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIOS(ID)
)
/

CREATE TABLE LOG_AUDITORIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSCRICAO_ID NUMBER NOT NULL,
    MOTIVO VARCHAR2(200) NOT NULL,
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_LOG_INSCRICAO FOREIGN KEY (INSCRICAO_ID)
        REFERENCES INSCRICOES(ID)
)
/

INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO) VALUES (1, 'Ana Souza', 'ana@email.com', 1, 100)
/
INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO) VALUES (2, 'Carlos Lima', 'carlos@email.com', 2, 50)
/
INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO) VALUES (3, 'Julia Rocha', 'julia@email.com', 3, 200)
/
INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO) VALUES (4, 'Marcos Silva', 'marcos@email.com', 2, 80)
/

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (1, 1, 'PRESENT', 100, 'NORMAL')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (2, 1, 'PRESENT', 120, 'VIP')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (3, 1, 'PRESENT', 140, 'NORMAL')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (4, 1, 'PRESENT', 160, 'NORMAL')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (5, 2, 'PRESENT', 200, 'VIP')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (6, 2, 'ABSENT', 200, 'NORMAL')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (7, 3, 'PRESENT', 300, 'NORMAL')
/
INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (8, 4, 'PRESENT', 250, 'VIP')
/

COMMIT
/
