BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOG_AUDITORIA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INSCRICOES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUARIOS (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PRIORIDADE NUMBER(1) NOT NULL,
    SALDO NUMBER(10,2) DEFAULT 0 NOT NULL
);

CREATE TABLE INSCRICOES (
    ID NUMBER PRIMARY KEY,
    USUARIO_ID NUMBER NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    VALOR_PAGO NUMBER(10,2) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_INSCRICOES_USUARIOS
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE LOG_AUDITORIA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSCRICAO_ID NUMBER,
    MOTIVO VARCHAR2(300) NOT NULL,
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO)
VALUES (1, 'Ana', 'ana@email.com', 1, 100);

INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO)
VALUES (2, 'Carlos', 'carlos@email.com', 2, 50);

INSERT INTO USUARIOS (ID, NOME, EMAIL, PRIORIDADE, SALDO)
VALUES (3, 'Julia', 'julia@email.com', 3, 200);

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO)
VALUES (1, 1, 'PRESENT', 100, 'NORMAL');

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO)
VALUES (2, 1, 'PRESENT', 150, 'VIP');

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO)
VALUES (3, 1, 'PRESENT', 200, 'NORMAL');

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO)
VALUES (4, 1, 'PRESENT', 250, 'NORMAL');

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO)
VALUES (5, 2, 'PRESENT', 300, 'VIP');

INSERT INTO INSCRICOES (ID, USUARIO_ID, STATUS, VALOR_PAGO, TIPO)
VALUES (6, 3, 'PRESENT', 400, 'NORMAL');

COMMIT;

-- Consultas úteis para conferência
-- SELECT * FROM USUARIOS ORDER BY ID;
-- SELECT * FROM INSCRICOES ORDER BY ID;
-- SELECT * FROM LOG_AUDITORIA ORDER BY ID;
